server:
  port: 8888
spring:
  kafka:
    bootstrap-servers: 120.27.246.207:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.ylf.demo.kafka.util.KafkaEncoder
    consumer:
      group-id: 0
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.ylf.demo.kafka.util.KafkaDecoder
      auto-offset-reset: latest
